# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

jobs:
- job: WindowsBuildAndTest
  displayName: 'Windows build and test'
  pool:
    vmImage: 'windows-latest'  
  steps:
  - task: NuGetToolInstaller@1
  - task: NuGetCommand@2
    inputs:
      restoreSolution: '$(solution)'
  - task: gittools.gitversion.gitversion-task.GitVersion@5
    displayName: GitVersion
    inputs:
      configFilePath: 'GitVersion.yml'  
  - task: VSBuild@1
    displayName: Build
    inputs:
      solution: '$(solution)'
      msbuildArgs: '/p:Version=$(GitVersion.AssemblySemVer) /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'  
  - task: VSTest@2
    displayName: Unit Test
    inputs:
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'
- job: LinuxBuildAndTest
  displayName: 'Linux build and test'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core sdk'
      inputs:
        packageType: sdk
        version: 3.1.x
        installationPath: $(Agent.ToolsDirectory)/dotnet
    - script: dotnet build
      displayName: Build
    - script: dotnet test
      displayName: Unit Test