# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

jobs:
- job: WindowsBuildAndTest
  displayName: 'Windows build and test'
  pool:
    vmImage: 'windows-latest'  
  steps:
    - task: gittools.gitversion.gitversion-task.GitVersion@5
      displayName: GitVersion
      inputs:
        configFilePath: 'GitVersion.yml'  
    - task: DotNetCoreCLI@2
      displayName: 'Build'
      inputs:
        command: 'build'
        configuration: '$(buildConfiguration)'  
        versionEnvVar: '$(GitVersion.AssemblySemVer)'
    - task: DotNetCoreCLI@2
      displayName: 'Domain Unit Test'
      inputs:
        command: 'test'
        projects: 'Timetable.Test/Timetable.Test.csproj'
        configuration: '$(buildConfiguration)'  
        nobuild: true
    - task: DotNetCoreCLI@2
        displayName: 'Webservice Unit Test'
        inputs:
          command: 'test'
          projects: 'Timetable.Test/Timetable.Web.Test.csproj'
          configuration: '$(buildConfiguration)'  
          nobuild: true
- job: LinuxBuildAndTest
  displayName: 'Linux build and test'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core sdk'
      inputs:
        packageType: sdk
        version: 3.1.x
        installationPath: $(Agent.ToolsDirectory)/dotnet
    - script: dotnet build -c Release
      displayName: 'Build'
    - script: dotnet test  -c Release ./Timetable.Test/Timetable.Test.csproj
      displayName: 'Domain Unit Test'
    - script: dotnet test  -c Release ./Timetable.Web.Test/Timetable.Web.Test.csproj
      displayName: 'Webservice Unit Test'