# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

variables:
  buildConfiguration: 'Release'
  GitVersion.SemVer: ''

jobs:
- job: WindowsBuildAndTest
  displayName: 'Windows build and test'
  pool:
    vmImage: 'windows-latest'  
  steps:
    - task: UseGitVersion@5
      displayName: gitversion
      inputs:
        runtime: 'core'
        versionSpec: '5.x'
        configFilePath: 'GitVersion.yml'
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: build
        configuration: $(buildConfiguration)  
        versioningScheme: byEnvVar
        versionEnvVar: $(GitVersion.SemVer)
    - task: DotNetCoreCLI@2
      displayName: 'Unit Test'
      inputs:
        command: test
        projects: |
          **/Timetable.Test/Timetable.Test.csproj
          **/Timetable.Web.Test/Timetable.Web.Test.csproj
        configuration: $(buildConfiguration)  
        nobuild: true
- job: LinuxBuildAndTest
  displayName: 'Linux build and test'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core sdk'
      inputs:
        packageType: sdk
        version: 3.1.x
        installationPath: $(Agent.ToolsDirectory)/dotnet
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: build
        configuration: $(buildConfiguration)  
    - task: DotNetCoreCLI@2
      displayName: 'Unit Test'
      inputs:
        command: test
        projects: |
          **/Timetable.Test/Timetable.Test.csproj
          **/Timetable.Web.Test/Timetable.Web.Test.csproj
        configuration: $(buildConfiguration)  
        nobuild: true